### ISSUE TITLE
Add scale-to-fit view mode

### ISSUE THREAD

**Issue by bk138** [bk138/multivnc#219]
# TODOs
- [x] add button
- [x] add menu entry
- [x] wire up
- [x] harmonise fullscreen button: make toggle as well
- [x] get correct factor for scaled view
- [x] impl scaling logic
- [x] impl centering logic
- [x] scale input as well
- [x] 2nd viewerwindow does not setup mode correctly
- [x] set mode should be remembered globally across restarts

# Resources
* https://docs.wxwidgets.org/3.2/classwx_d_c.html

**Comment by muava12** [comment]
Yes we need this feature. for now is there a way to make it fit on window?

**Comment by bk138** [comment]
WIP, see the PR 🙂

**Comment by geekley** [comment]
There is so much wasted spaced too... for starters, you could unify the tab bar, toolbar, status bar and menus in a single row. You could even have drop-downs for the server and bookmarks too, so everything is in a single row.

Also, what is the point of fullscreen if most elements will still occupy space?
It doesn't remove toolbar, status bar, statistics and the tabs bar.
The only thing that should be in the fullscreen is the other device's screen, and a way to exit fullscreen, which could be:
- a key combo (e.g. Ctrl+F11) that's never grabbed by the device, showed when you enter fullscreen (like Firefox does)
- a button to exit fullscreen that appears when you hover the top edge of the screen (like Firefox); or that is always visible on top of the content (without taking space away from it)

This way you could maximize usable screen space, which would be great along with this feature request.

**Comment by bk138** [comment]
@geekley please open a separate issue about this or better yet, a full PR :-)
